### ISSUE TITLE
Deaktivierte Station unklar

### ISSUE THREAD

**Issue by kaspar-allenbach** [cstuder/QuoBikeIs#14]
Wenn eine Station deaktiviert wird kommt das:

![Bildschirmfoto 2019-09-03 um 11 13 33](https://user-images.githubusercontent.com/762213/64160242-ee6ca280-ce3b-11e9-974c-de611facb37c.png)

So sieht man aber nicht welche Station das überhaupt ist. Gibt der dienst den namen nicht mehr retour?

**Comment by cstuder** [comment]
Nein, das ist die Art und Weise wie Publibike seine Stationen offline nimmt: Mit einer Namensänderung.

Kann ich nichts machen...

**Comment by kaspar-allenbach** [comment]
Habs mir so halbers gedacht. Sehr hacky, einfach den Namen ändern 🤣
